"""Command: extract-keywords — TF-IDF over title+abstract, store ranked keywords."""

from __future__ import annotations

import json
from pathlib import Path

import click
import polars as pl
from rich.console import Console
from rich.table import Table

console = Console()

_MIN_DOC_CHARS = 20
_TOKEN_PATTERN = r"(?u)\b[a-zA-Z][a-zA-Z\-]+\b"


def _load_dataframe(path: Path) -> pl.DataFrame:
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        return pl.read_excel(path)
    if suffix == ".csv":
        return pl.read_csv(path, null_values="n/a", infer_schema_length=10000)
    raise click.ClickException(
        f"Unsupported input format '{suffix}'. Use .xlsx, .xls, or .csv."
    )


def _build_documents(df: pl.DataFrame, title_col: str, abstract_col: str) -> list[str]:
    missing = [c for c in (title_col, abstract_col) if c not in df.columns]
    if missing:
        raise click.ClickException(
            f"Column(s) not found: {missing}. Available columns: {df.columns}"
        )
    docs: list[str] = []
    for row in df.iter_rows(named=True):
        title = (row.get(title_col) or "").strip()
        abstract = (row.get(abstract_col) or "").strip()
        combined = f"{title}. {abstract}".strip(". ").strip()
        if len(combined) >= _MIN_DOC_CHARS:
            docs.append(combined)
    return docs


def _score_terms(
    docs: list[str], ngram_min: int, ngram_max: int, min_df: int, max_df: float
) -> list[tuple[str, float]]:
    from sklearn.feature_extraction.text import TfidfVectorizer

    vectorizer = TfidfVectorizer(
        ngram_range=(ngram_min, ngram_max),
        stop_words="english",
        min_df=min_df,
        max_df=max_df,
        lowercase=True,
        token_pattern=_TOKEN_PATTERN,
    )
    matrix = vectorizer.fit_transform(docs)
    mean_scores = matrix.mean(axis=0).A1
    terms = vectorizer.get_feature_names_out()
    pairs = list(zip(terms, mean_scores))
    pairs.sort(key=lambda p: p[1], reverse=True)
    return pairs


def _print_table(top: list[tuple[str, float]]) -> None:
    table = Table(title=f"Top {len(top)} TF-IDF keywords", show_lines=False)
    table.add_column("Rank", justify="right", style="cyan", no_wrap=True)
    table.add_column("Keyword", style="white")
    table.add_column("Mean TF-IDF", justify="right", style="green")
    for i, (term, score) in enumerate(top, start=1):
        table.add_row(str(i), term, f"{score:.4f}")
    console.print(table)


def _confirm_overwrite(path: Path, force: bool) -> bool:
    if not path.exists() or force:
        return True
    import questionary

    return bool(questionary.confirm(f"{path} exists. Overwrite?", default=False).ask())


def _write_output(
    pairs: list[tuple[str, float]],
    output_path: Path,
    fmt: str,
    source: Path,
    params: dict,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if fmt == "json":
        payload = {
            "_meta": {"source": str(source), "params": params},
            "keywords": [{"term": t, "score": float(s)} for t, s in pairs],
        }
        output_path.write_text(json.dumps(payload, indent=4) + "\n", encoding="utf-8")
    elif fmt == "csv":
        import csv

        with output_path.open("w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["rank", "term", "score"])
            for i, (t, s) in enumerate(pairs, start=1):
                writer.writerow([i, t, f"{s:.6f}"])
    elif fmt == "txt":
        lines = [
            f"# Generated by openalex extract-keywords from {source}",
            f"# params: {params}",
            *[t for t, _ in pairs],
        ]
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    else:
        raise click.ClickException(f"Unknown --format '{fmt}'.")


@click.command("extract-keywords")
@click.argument("input_file", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--title-col", default="Article Title", show_default=True, help="Title column name")
@click.option("--abstract-col", default="Abstract", show_default=True, help="Abstract column name")
@click.option("--top-n", type=int, default=50, show_default=True, help="Number of keywords to keep")
@click.option("--ngram-min", type=int, default=2, show_default=True, help="Minimum n-gram size")
@click.option("--ngram-max", type=int, default=3, show_default=True, help="Maximum n-gram size")
@click.option("--min-df", type=int, default=2, show_default=True, help="Minimum document frequency")
@click.option("--max-df", type=float, default=0.85, show_default=True, help="Maximum document frequency (proportion)")
@click.option(
    "--format",
    "fmt",
    type=click.Choice(["json", "csv", "txt"], case_sensitive=False),
    default="json",
    show_default=True,
    help="Output file format",
)
@click.option(
    "--output",
    "output_path",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Where to write keywords. Default: config/tfidf_keywords.<format>",
)
@click.option("--no-write", is_flag=True, help="Print only, skip writing file")
@click.option("--force", is_flag=True, help="Overwrite output file without prompting")
def extract_keywords_command(
    input_file: Path,
    title_col: str,
    abstract_col: str,
    top_n: int,
    ngram_min: int,
    ngram_max: int,
    min_df: int,
    max_df: float,
    fmt: str,
    output_path: Path | None,
    no_write: bool,
    force: bool,
) -> None:
    """Run TF-IDF over title+abstract in INPUT_FILE and store ranked keywords.

    Output is a flat list of keywords (with scores). Query construction is left
    to the caller — use the file however you like.
    """
    if ngram_min < 1 or ngram_max < ngram_min:
        raise click.ClickException("Require 1 <= --ngram-min <= --ngram-max.")
    if top_n < 1:
        raise click.ClickException("--top-n must be >= 1.")

    fmt = fmt.lower()
    if output_path is None:
        output_path = Path(f"config/tfidf_keywords.{fmt}")

    df = _load_dataframe(input_file)
    docs = _build_documents(df, title_col, abstract_col)
    if not docs:
        console.print("[bold red]✗ No usable documents after filtering.[/bold red]")
        raise SystemExit(1)
    console.print(f"[dim]Loaded {len(docs)} documents from {input_file}[/dim]")

    pairs = _score_terms(docs, ngram_min, ngram_max, min_df, max_df)
    if not pairs:
        console.print("[bold red]✗ TF-IDF produced no terms (relax --min-df / --max-df).[/bold red]")
        raise SystemExit(1)

    top = pairs[:top_n]
    _print_table(top)

    if no_write:
        return

    if not _confirm_overwrite(output_path, force):
        console.print("[yellow]Skipped writing output file.[/yellow]")
        return

    params = {
        "top_n": top_n,
        "ngram_min": ngram_min,
        "ngram_max": ngram_max,
        "min_df": min_df,
        "max_df": max_df,
    }
    _write_output(top, output_path, fmt, input_file, params)
    console.print(f"[green]✓ Wrote {len(top)} keywords to [cyan]{output_path}[/cyan][/green]")
